language: node_js
node_js:
- '4.2'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
sudo: false
services:
before_install:
- openssl aes-256-cbc -K $encrypted_a2f47a5da016_key -iv $encrypted_a2f47a5da016_iv
  -in .travis/travis_rsa.pem.enc -out .travis/travis_rsa.pem -d
- npm update -g npm
- npm --version
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- pip install codecov
before_script:
# seems to be necessary (for coveralls push in after success) due to the way travis clones the repo:
# git clone --depth=50 --branch=master https://github.com/lathonez/clicker.git lathonez/clicker
- git checkout master
after_script:
notifications:
  email: true
after_failure: cat /home/travis/build/lathonez/clicker/npm-debug.log
branches:
  only:
  - master
after_success:
# push compiled TS to test folder in git for reference in coveralls
- eval "$(ssh-agent -s)"
- chmod 600 .travis/travis_rsa.pem
- ssh-add .travis/travis_rsa.pem
- rm .gitignore
- git add www/build/test/app
- git remote rm origin                                       # originally cloned by travis on https
- git remote add origin git@github.com:lathonez/clicker.git  # ditto
- git -c user.name='travis' -c user.email='travis@travis-ci.org' commit -m "updating compiled tests [ci skip]" # dont want this triggering another build
- git push origin master
# dont send to coveralls until _after_ we've pushed the compiled test code
- cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js && rm -rf coverage
- codecov
# push to ionic (should be deploy really)
- npm install -g cordova ionic
- ionic platform add android
- ionic build android
- ionic upload --email $IONIC_EMAIL --password $IONIC_PASSWORD
