language: node_js
node_js:
# - uncomment these to allow concurrent builds on the different node envs
# - '4.0'
# - '4.1'
  - '4.2'
sudo: false
services:
before_install:
- npm update -g npm
- npm --version
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
notifications:
  email: true
after_failure: cat /home/travis/build/lathonez/clicker/npm-debug.log
branches:
  only:
  - master