#
# Configuration
#

sudo: required
dist: trusty

notifications:
  email: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - google-chrome
    packages:
      - google-chrome-stable

branches:
  only:
    - master

#
# Build Lifecycle:
#

before_install:
  - nvm use 4.1.2
  - npm install -g cordova ionic

install:
  - npm install
  - ionic state restore # install cordova stuff from package.json
  - npm run webdriver-update

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - chromium-browser --version

script:
  - npm test                             # unit tests
  - npm run build                        # ionic build
  # Serve with python as ionic serve needs interaction
  - cd www && python -m SimpleHTTPServer 8100 >> python_serve.log 2>&1 &
  - npm run e2e                          # run e2e tests against ionic

after_failure:
  - cat /home/travis/build/lathonez/clicker/python_serve.log
  - cat /home/travis/build/lathonez/clicker/ionic_serve.log

after_success:
  # Send coverage info off to cloud ppl
  - cat coverage/lcov.info | ./node_modules/.bin/codecov

before_deploy:
  - ionic build android

deploy:
  provider: script
  script: .travis/deploy.sh
  skip_cleanup: true
