language: node_js
node_js:
# - uncomment these to allow concurrent builds on the different node envs
# - '4.0'
# - '4.1'
  - '4.2'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
sudo: false
services:
before_install:
- npm update -g npm
- npm --version
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
after_script:
 - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js && rm -rf coverage
notifications:
  email: true
after_failure: cat /home/travis/build/lathonez/clicker/npm-debug.log
branches:
  only:
  - master
after_success:
  - npm install -g cordova ionic
  - ionic platform add android
  - ionic build android
  - ionic upload --email $IONIC_EMAIL --password $IONIC_PASSWORD
