#
# Clicker CircleCI 2.0 configuration file
#
version: 2
jobs:
  build:
    docker:
      # Image info:
      #  - Ubuntu 16.10
      #  - node 7.10.1
      #  - ionic 3.4.0
      #  - cordova 7.0.1
      #  - chrome latest stable
      - image: lathonez/ionic-selenium:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # dump env for debug
      - run: ionic info

      # run tests!
      - run: npm run lint
      - run: npm run test-ci
      - run: npm run e2e